---
apiVersion: v1
kind: Namespace
metadata:
  name: workshop

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: workshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: public.ecr.aws/u2g6w7p2/eks-workshop-demo/simplewebserver:1.0
        name: simplewebserver

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: workshop
spec:
  type: ClusterIP
  ports:
    - port: 80 
      name: http 
  selector:
    app: frontend

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  namespace: workshop
  labels:
    app.kubernetes.io/name: LoadBalancerController
  name: webappalb
spec:
  controller: eks.amazonaws.com/alb

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: workshop
  name: ingress
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: webappalb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: webappalb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
